---
title: "template"
author: "JT"
date: "2/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	collapse = TRUE,
	options(scipen = 999)
)

cat("\014") # Clear your console
rm(list = ls()) # Clear your environment

# Load in header file
source("/Users/jan/blog/jantau/content/post/header.R")
```



Den f체r diesen Beitrag erstellten Code findest du hier: [https://github.com/jantau/jantau](https://github.com/jantau/jantau/tree/main/content/post){target="_blank"}

Hat dir der Post gefallen? [Melde dich f체r meinen Newsletter an](https://tinyletter.com/jantau), um 체ber neue Beitr채ge informiert zu werden.


```{r}
#----------------------------------------------------------------------------
# Ggplot Template for caption and axis
#----------------------------------------------------------------------------

set.seed(42)  ## for sake of reproducibility
n <- 10
dat <- data.frame(
  years = 1:n,
  group = rep(LETTERS[1:10]),
  money = sample(30000:50000, n, replace = TRUE)
)


ggplot(dat, aes(x = group,
                y = money,)) +
  geom_point() +
  theme_jantau +
  labs(
    title = "Titel",
    subtitle = "Untertitel",
    caption = "Datenanalyse u. Visualisierung: jantau.com | Daten: finance.yahoo.com") +
  theme(panel.background = element_rect(fill = NA, color = "grey"),
        axis.title.y = element_blank(),
        axis.title.x = element_blank())


```


