---
title: gewichtung
author: Jan Tau
date: '2021-01-07'
slug: gewichtung
categories: []
tags: []
subtitle: 'gewichtung_test'
summary: 'gewichtung_test'
authors: []
lastmod: '2021-01-07T13:24:38+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	collapse = TRUE,
	options(scipen = 999)
)

cat("\014") # Clear your console
rm(list = ls()) # Clear your environment

# Load in header file
source("/Users/jan/blog/jantau/content/post/header.R")
```


```{r}
archive_weight_all_long <- read_csv(file = "/Users/jan/blog/jantau/content/post/2021-02-27-portfolio-und-aktien-gewichtung/weight_all_long.csv")
```

```{r}
library(highcharter)
library(widgetframe)
library(htmlwidgets)

pal <- got(4, option = "Daenerys", direction = 1)

archive_weight_all_long <- archive_weight_all_long %>% 
  filter(sum >= 0.5) %>%
  mutate(value = value * 100)

hc <- hchart(archive_weight_all_long,
    'bar', hcaes(x = 'Symbol', y = 'value', group = 'name'),
    stacking = "normal"
    ) %>%
  hc_title(text = "Gewichtung einzelner Aktien im Gesamtportfolio") %>%
  hc_colors(pal) 

#frameWidget(hc)

```

```{r}
saveWidget(hc, file = "hc.html", selfcontained = TRUE)
```

<iframe seamless src="hc.html" width="100%" height="500"></iframe>

```{r}
# htmlwidgets::saveWidget(frameableWidget(hc), file = "hc.html", selfcontained = TRUE)

#<!--html_preserve-->
#<iframe height="500" width="100%" frameborder="no" src="hc.html"> </iframe>
#<!--/html_preserve-->

#<iframe height="500" width="100%" frameborder="no" #src="https://www.highcharts.com/demo/line-basic"> </iframe>
```



Den für diesen Beitrag erstellten Code findest du hier: [https://github.com/jantau/jantau](https://github.com/jantau/jantau/tree/main/content/post){target="_blank"}
